trigger:
- main  # Triggers pipeline on commits to main branch

variables:
  azureSubscription: 'L’EVATE Inc.'  
  appName: 'your-app-service-name'  
  resourceGroup: 'your-resource-group'  
  buildConfiguration: 'Release'  

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build job
    pool:
      vmImage: 'ubuntu-latest'  # Use Microsoft-hosted Ubuntu agent
    
    steps:
    # Install Node.js runtime
    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'
      displayName: 'Install Node.js'
    
    # Install dependencies and build application
    - script: |
        npm install
        npm run build --if-present
      displayName: 'Install dependencies and build'
    
    # Package build artifacts into zip file
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
        replaceExistingArchive: true
      displayName: 'Create deployment package'
    
    # Publish zip artifact for deployment stage
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/app.zip'
        ArtifactName: 'drop'
        publishLocation: 'Container'

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build  # Requires successful build first
  jobs:
  - deployment: Deploy
    displayName: Deploy job
    environment: 'production'  # Deployment environment
    pool:
      vmImage: 'ubuntu-latest'
    
    strategy:
      runOnce:  # Standard deployment strategy
        deploy:
          steps:
          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'drop'
              downloadPath: '$(System.ArtifactsDirectory)'
          
          # Stop App Service before deployment
          - task: AzureAppServiceManage@0
            inputs:
              azureSubscription: '$(azureSubscription)'
              Action: 'Stop Azure App Service'
              WebAppName: '$(appName)'
          
          # Deploy zip package to App Service
          - task: AzureAppServiceManage@0
            inputs:
              azureSubscription: '$(azureSubscription)'
              Action: 'Deploy Azure App Service'
              WebAppName: '$(appName)'
              Package: '$(System.ArtifactsDirectory)/drop/app.zip'
          
          # Start App Service after deployment
          - task: AzureAppServiceManage@0
            inputs:
              azureSubscription: '$(azureSubscription)'
              Action: 'Start Azure App Service'
              WebAppName: '$(appName)'
          
          # Swap staging slot with production (blue-green deployment)
          - task: AzureAppServiceManage@0
            inputs:
              azureSubscription: '$(azureSubscription)'
              Action: 'Swap Slots'
              WebAppName: '$(appName)'
              ResourceGroupName: '$(resourceGroup)'
              SourceSlot: 'staging'
              SwapWithProduction: true